type LoadGroupsOfbusinessByBusinessIdResponse = MorabaaItemSolutionDomainInterfacesIGroup;


type LoadItemsPendingV2Response = MorabaaItemSolutionDomainInterfacesIItem;


type LoadItemsOfownerResponse = MorabaaItemSolutionRESTAPIDTOsResponsesMyMorabaaItemResponse;


type LoadItemsResponse = MorabaaItemSolutionDomainInterfacesIItem;


type LoadItemsOfgroupByGroupIdResponse = MorabaaItemSolutionRESTAPIDTOsResponsesRestaurantMenuItemResponse;


type LoadOffersResponse = MorabaaItemSolutionRESTAPIDTOsResponsesItemOfferResponse;


type LoadStoresOfbusinessByBusinessIdResponse = MorabaaItemSolutionDomainInterfacesIStore;


type LoadAccountsResponse = SalesReportAPIDTOsResponsesAccountWithBalancesResponse;


type LoadAccountsOfbusinessPendingByBusinessIdResponse = SalesReportAPIEntitiesAccount;


type LoadBusinesstransactionsOfbusinessV2ByBusinessIdResponse = SalesReportAPIEntitiesBusinessTransaction;


type LoadSalesperdayByBusinessIdResponse = SalesReportAPIEntitiesSalesPerDay;


type LoadTransactionsExpensesByBusinessIdResponse = SalesReportAPIEntitiesTransaction;

